### ISSUE TITLE
Error using markup_text-1.0.1 (?)

### ISSUE THREAD

**Issue by zalekbloom** [poqueque/markup_text#1]
I am not a computer expert, so maybe I am wrong, here is what happened:
My app is using markup_text-1.0.1 and after I issued  from VSCode the commands: 
flutter build apk --split-per-abi

here is what I got: 
 Building with sound null safety 

/C:/Users/hayor/AppData/Local/Pub/Cache/hosted/pub.dev/markup_text-1.0.1/lib/src/markup_parser.dart:8592:37: Error: Member not found: 'whatsapp'.
      case "whatsapp": return Icons.whatsapp;
                                    ^^^^^^^^
/C:/Users/hayor/AppData/Local/Pub/Cache/hosted/pub.dev/markup_text-1.0.1/lib/src/markup_parser.dart:8593:43: Error: Member not found: 'whatsapp_sharp'.
      case "whatsapp_sharp": return Icons.whatsapp_sharp;
                                          ^^^^^^^^^^^^^^
/C:/Users/hayor/AppData/Local/Pub/Cache/hosted/pub.dev/markup_text-1.0.1/lib/src/markup_parser.dart:8594:45: Error: Member not found: 'whatsapp_rounded'.
      case "whatsapp_rounded": return Icons.whatsapp_rounded;
                                            ^^^^^^^^^^^^^^^^
/C:/Users/hayor/AppData/Local/Pub/Cache/hosted/pub.dev/markup_text-1.0.1/lib/src/markup_parser.dart:8595:46: Error: Member not found: 'whatsapp_outlined'.
      case "whatsapp_outlined": return Icons.whatsapp_outlined;
                                             ^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1154

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Running Gradle task 'assembleRelease'...                           11.3s
Gradle task assembleRelease failed with exit code 1
PS D:\flutter_projects\spanish_rules> flutter pub outdated
Resolving...
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name  Current  Upgradable  Resolvable  Latest

direct dependencies: all up-to-date.

dev_dependencies: all up-to-date.

transitive dependencies:
image         *3.3.0   *3.3.0      *3.3.0      4.0.13
all dependencies are up-to-date.
PS D:\flutter_projects\spanish_rules> 

Please advice,

Thanks,

zb

**Comment by poqueque** [comment]
What version of Flutter are you using? Could you please add the output of flutter doctor?

**Comment by poqueque** [comment]
Well it looks they removed some icons on Flutter 3.7:
https://github.com/flutter/flutter/issues/119608

I'll fix it in a new version

**Comment by poqueque** [comment]
Fixed on version 1.0.2
