### ISSUE TITLE
 markup_text-1.0.2 possible problem.

### ISSUE THREAD

**Issue by zalekbloom** [poqueque/markup_text#2]
I found this package very useful, but I cannot compile my app which is using this package. Not a big deal for me – I wrote it for myself and I found a solution – I debug my app on my physical device and I leaving it there.

Why I think the problem if with this package:
First time I used this package after the command: “flutter build apk --split-per-abi” I was getting error:
Dart snapshot generator failed with exit code -1073741571
and program was looping.

Recently in my other working app I replace Text widget with MarkupText widget (added the package and the import statement too) – the debug was working OK, but the command “flutter build apk --split-per-abi” gave me the same errors.

I did some search: 
Dart snapshot generator is a tool that compiles Dart code ahead-of-time into a snapshot file, which contains the pre-compiled machine code of the application. This snapshot file can be loaded by the Dart runtime to start the application more quickly, without having to compile the code at runtime. This is particularly useful for mobile and embedded platforms, where startup time and memory usage are critical factors.

I also found that some people explained that “Dart snapshot generator failed” is related to virtual memory, and I notice markup_parser.dart has 17,000 statement.

I am not an expert, only a beginner in Flutter, so quite possible I am wrong – there are only my speculations.

Thanks,

zb

**Comment by poqueque** [comment]
@zalekbloom 
Can you provide flutter doctor -v?

**Comment by zalekbloom** [comment]
Sure!

flutter doctor -v 
[√] Flutter (Channel master, 3.8.0-10.0.pre.1, on Microsoft Windows [Version
    10.0.22621.1105], locale en-US)
    • Flutter version 3.8.0-10.0.pre.1 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 001c4951b6 (6 days ago), 2023-02-09 20:14:10 -0500
    • Engine revision e1d0032029
    • Dart version 3.0.0 (build 3.0.0-218.0.dev)
    • DevTools version 2.21.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\hayor\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)     
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community        
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version       
      10.0.22621.1105]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.100     
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.41     

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
PS D:\flutter_projects\spanish_rules>

**Comment by zalekbloom** [comment]
I made a change to your package and now I can create the apk files.  As I said - I am not expert, so I am not sure if it will work for everyone.  
In markup_parser.dart I got rid of the "static IconData? getIconData(String? name)" part. I don't know what this part supposed to do, I guess something with icons, but I need only the part where I can the easy way to format text. It needs a simple change in  markup_text.dart too - so I got rid of 17000 statements and I can compile my app.
Thanks!

zb

**Comment by DavidKlant** [comment]
Encountered the same error. Posted my stacktrace and flutter doctor on StackOverflow (in case this helps to fix it):
https://stackoverflow.com/questions/76227524/flutter-aot-snapshotter-exited-with-code-1073741571

**Comment by j-fbriere** [comment]
Since the last modifications (commit f18492fa2cfc1014203204e624f6a27e71bc88b8 of may the 18th), I can now execute a build release for android without any AOT error.

Thank you.

**Comment by poqueque** [comment]
Fixed on 1.0.3
