### ISSUE TITLE
Can you possibly set the Hover color when URL link?

### ISSUE THREAD

**Issue by Govindbetterlives** [poqueque/markup_text#5]
Can you possibly set the Hover color when URL link?

**Comment by poqueque** [comment]
Could you please provide an example of your request?

**Comment by Govindbetterlives** [comment]
Hi,
Thanks for replying,

My request is 
![image](https://github.com/poqueque/markup_text/assets/81243940/415f5f28-f891-4ac3-9822-254728767a2e)

**Comment by poqueque** [comment]
It looks it's not an easy way to add hover color to TextSpan. Feel free to add a PR with this change if you find the way.
