### ISSUE TITLE
Member not found for markup_text in dart (unable to find icons)

### ISSUE THREAD

**Issue by vverma9** [poqueque/markup_text#8]
I am unable to use this package due to [this error](https://stackoverflow.com/questions/76310070/member-not-found-for-markup-text-in-dart-unable-to-find-icons), please help!

Output of flutter doctor below:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.25)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.78.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

```

**Comment by poqueque** [comment]
Could you please add the output of flutter doctor? Thanks!

**Comment by vverma9** [comment]
> Could you please add the output of flutter doctor? Thanks!

I added it to the post.

**Comment by poqueque** [comment]
Updated minimum Flutter version in pubspec.yaml. The versions 1.0.3 and 1.0.4 of the package will need at least Flutter 3.10.0

If you have to use Flutter 3.3.4, you should use a previous version of the package.

**Comment by vverma9** [comment]
which version should I use for mine ?

**Comment by poqueque** [comment]
Version 1.0.2 is built with Flutter 3.7.0 but it may work. Version 1.0.1 should work for sure. You can check Flutter versions used in the [CHANGELOG](https://github.com/poqueque/markup_text/blob/master/CHANGELOG.md).
